/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Skeletal_raven_arts (https://sketchfab.com/skeletal_raven_arts)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/prototype-knight-polished-4b414735d98f483289a7a5a4d8b49ac7
Title: Prototype Knight Polished
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import knightScene from '../assets/3d/knight.glb'

const Knight = ({currentAnimation, ...props}) => {

  const group = useRef()
  const { nodes, materials, animations } = useGLTF(knightScene)
  const { actions } = useAnimations(animations, group)

  
  useEffect(() =>{    
    Object.values(actions).forEach((actions) => actions.stop());

    if(actions[currentAnimation]) {
      actions[currentAnimation].play();
      actions[currentAnimation].timeScale = 0.5; 
    }
  }, [actions, currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Chibi_Knight_Rig_264">
                <group name="GLTF_created_0">
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Chibi_Knight}
                    skeleton={nodes.Object_7.skeleton}
                  />
                  <group name="Chibi_Knight_263" />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

export default Knight;